<a href="https://colab.research.google.com/github/johnbyronA/Fundamentos_Clases/blob/main/Copia_de_Copia_de_Copia_de_Numpy_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Concatenación de arreglos**


La concatenación, o unión de dos arreglos en NumPy, se realiza principalmente a través de la función `concatenate`:

In [6]:
l=[1,2,3]
m=[4,5,6]

In [3]:
l+m

[1, 2, 3, 4, 5, 6]

Podemos concatenar más de dos arreglos al tiempo:

In [7]:
import numpy as np

x=np.array(l)
y=np.array(m)

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [5]:
z=np.array([7,8,9])

`concatenate` también se puede usar para arreglos bidimensionales. Recuerde que las filas corresponden al eje 1 (axis = 1) y las columnas al eje 0 (axis = 0)


<p><img alt="Colaboratory logo" height="300px" src="https://i.imgur.com/KYPgvhf.png" align="left" hspace="10px" vspace="0px"></p>

In [7]:
a = np.arange(8,14).reshape(3,2)
a

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [8]:
np.concatenate([a,a], axis=0)

array([[ 8,  9],
       [10, 11],
       [12, 13],
       [ 8,  9],
       [10, 11],
       [12, 13]])

Si queremos realizar la concatenación a lo largo del eje 1, debemos especificar el eje por medio de un argumento por palabra clave:

In [9]:
np.concatenate([a,a], axis=1)

array([[ 8,  9,  8,  9],
       [10, 11, 10, 11],
       [12, 13, 12, 13]])

La función `vstack()` es equivalente a la concatenación a lo largo del primer eje (axis=0). Al igual que `concatenate()`, recibe como argumento una secuencia de arreglos que, en este caso, deben tener la misma forma a lo largo de todos los ejes, excepto el primero. Los arreglos unidimensionales deben tener la misma longitud:

In [11]:
# dimensiones mixtas
a= np.array([1,2,3])
b=np.arange(3,9).reshape(2,3)

np.vstack([a,b])

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
a=np.array([[1],[2]])
b=np.array([[4],[5],[6]])
np.vstack([a,b])

array([[1],
       [2],
       [4],
       [5],
       [6]])

In [16]:
#No se puede hacer si presentan dimensionalidad diferente
a=np.array([1,2,3])
b=np.arange(3,9).reshape(3,2)

try:
  np.vstack([a,b])
except Exception as e:
  print(e)

print("hola mundo")

all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2
hola mundo


Similarmente, la función `hstack()` realiza una concatenación a lo largo del segundo eje (axis=1), y los arreglos que toma como argumento deben coincidir en la forma a lo largo de este eje. Los arreglos unidimensionales pueden ser de cualquier longitud

In [19]:
#dimensiones mixtas
a=np.array([[1,2],[3,4]])
b=np.arange(5,11).reshape(2,3)

np.hstack([a,b])

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

In [ ]:
#arreglos unidimensionales


<p><a name="ind"></a></p>

# **Indexación y segmentación**

Los arreglos de NumPy tienen la misma semántica de indexación y segmentación que las listas de Python cuando se trata de acceder a elementos o subarreglos.




In [20]:
a = np.arange(12)

print(f"a: {a}")
print()
print(f"a[3]: {a[3]}")
print()
print(f"a[2:6]: {a[2:8:3]}")

a: [ 0  1  2  3  4  5  6  7  8  9 10 11]

a[3]: 3

a[2:6]: [2 5]


Debido a que los arreglos de NumPy son n-dimensionales, podemos segmentar a lo largo de todos y cada uno de los ejes. Consideremos la siguiente lista de listas en Python

In [22]:
# definiendo una lista de listas de forma (3,3)
L = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Por ejemplo, si queremos crear una lista de Python que contenga todas las filas y las primeras dos columnas de la lista L podríamos escribir

In [24]:
l_arr=np.array(L)
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
for fila in L:
  print(fila[:2])

El número de ciclos `for` anidados que se necesita para segmentar listas de listas es igual al número de dimensiones menos uno (en este caso $2-1=1$).

En NumPy, en lugar de indexar por un segmento, podemos indexar por una tupla de segmentos, cada uno de los cuales actúa en sus propias dimensiones. Definamos el arreglo `L` con NumPy y realicemos la segmentación anterior:


In [25]:
l_arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

Los ciclos `for` para la segmentación multidimensional son manejados implícitamente por NumPy. Esto hace que realizar segmentaciones complejas sea mucho más rápido que escribir los ciclos `for` explícitamente en Python. Veamos algunos ejemplos:

In [26]:
#creamos un arreglo de dimensiones 4x4
a=np.arange(16).reshape(4,4)

In [27]:
#seleccionar la primer fila (equivalente a a[0,:])
a[0,:]

array([0, 1, 2, 3])

In [28]:
# seleccionar la primera columna
a[:,0]

array([ 0,  4,  8, 12])

In [30]:
#segmentar las filas pares y las columnas impares.
a[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [32]:
#segmentar la matriz interna de 2x2.
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [44]:
#invertir las primeras 3 filas, tomando las primeras 3 columnas
a[2::-1,:3]

array([[ 8,  9, 10],
       [ 4,  5,  6],
       [ 0,  1,  2]])

**Ejercicio 1**: Escriba un programa para crear un nuevo arreglo que sea el promedio de cada triplete consecutivo de elementos del siguiente arreglo

<p><img alt="Colaboratory logo" height="70px" src="https://i.imgur.com/XoHovZd.png" align="left" hspace="10px" vspace="0px"></p>

In [64]:
a= np.array([[1,2,3],[2,4,6],[1,2,12],[0,-12,6]])
b= np.mean(a[0])
c= np.mean(a[1])
d= np.mean(a[2])
e= np.mean(a[3])
print(b)
print(c)
print(d)
print(e)

2.0
4.0
5.0
-2.0


In [63]:
a = [1,2,3,2,4,6,1,2,12,0,-12,6]
arr=np.array(a).reshape(4,3)
np.mean(arr,axis=1)

array([ 2.,  4.,  5., -2.])

<p><a name="enm"></a></p>

## **Enmascaramiento**

El enmascaramiento aparece cuando deseamos extraer, modificar, o manipular valores en un arreglo de acuerdo con algún criterio.

Ya vimos cómo utilizar ufuncs para operaciones aritméticas básicas y otro tipo de operaciones más complejas. NumPy implementa también operadores de comparación como ufuncs:

In [8]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
x<5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

El resultado es un arreglo booleano. Dado un arreglo booleano, hay una serie de operaciones útiles que podemos implementar.

Podemos utilizar la función `np.sum` junto con los operadores de comparación para realizar conteos dentro del arreglo:

In [11]:
# numero de elementos menores a 5
np.sum(x<5)

5

In [13]:
np.sum(x[x<5])

10

In [14]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Con `np.sum` podemos realizar este tipo de conteos a lo largo de las filas o columnas, utilizando el argumento por palabra clave `axis`:

In [15]:
# numero de elementos menores a 6 por columna
np.sum(x<5,axis=0)

array([3, 2, 0])

In [ ]:
# numero de elementos menores a 6 por fila
np.sum(x<5,axis=1)

Podemos también tener múltiples condiciones en un conteo, utilizando los operadores lógicos `&` (and) y `|` (or)

In [16]:
# verdadero si ambos verdaderos
np.sum((x>1)&(x<5))

3

In [18]:
# verdadero en caso en que alguno de los dos sea verdadero
np.sum((x<1)|(x>5))

4

Una herramienta muy poderosa es usar los arreglos booleanos como máscaras, para seleccionar subconjuntos particulares de los datos mismos.

Volviendo a nuestra arreglo `x` anterior, supongamos que queremos un arreglo de todos los valores en `x` que sean menores que, digamos, 5. Para seleccionar estos valores del arreglo, simplemente podemos indexar con este arreglo booleano; esto se conoce como una operación de enmascaramiento:

In [19]:
x[x<5]

array([0, 1, 2, 3, 4])

Lo que se devuelve es un arreglo unidimensional con todos los valores que cumplen la condición; en otras palabras, todos los valores en las posiciones en las que el arreglo de máscara es `True`.

**Ejercicio 2:** Escriba una función que, dado un número entero `n`, muestre:

* Un arreglo con los primeros números pares hasta `n`.
* Un arreglo con los primeros números múltiplos de tres hasta `n`.

**Ejercicio 3:** Escribir un programa que lea `n` números enteros, calcule y muestre la suma de los pares y el producto de los impares.

In [36]:
def leer_enteros(n):
  arr=np.arange(n)
  pares=arr[arr%2 == 0]
  impares=arr[arr%3 == 0]
  return pares,impares

leer_enteros(10)

(array([0, 2, 4, 6, 8]), array([0, 3, 6, 9]))

<p><a name="sof"></a></p>

# **Indexación sofisticada**

Anteriormente vimos cómo acceder y modificar porciones de arreglos usando índices simples (por ejemplo, `arr[0]`), segmentos (por ejemplo, `arr[: 5]`) y máscaras booleanas (por ejemplo, `arr[arr> 0]`). Veremos ahora otro estilo de indexación de arreglos, conocido como *indexación sofisticada*, la cual nos permite acceder y modificar muy rápidamente subconjuntos complicados de los valores de un arreglo.

La indexación sofisticada es conceptualmente simple: significa pasar una lista de índices en lugar de un entero, para acceder a múltiples elementos del arreglo a la vez. Veamos un ejemplo:

In [38]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
print(a[0],a[4],a[6])

10 14 16


In [40]:
indices=[0,4,6]
a[indices]

array([10, 14, 16])

Con el indexado sofisticado, la forma del resultado refleja la forma del arreglo de índices más que la forma del arreglo que se está indexando:

In [41]:
a=np.arange(0,91,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
# creamos arreglo de indices con forma (2,2)
indi=np.array([[3,7],[4,9]])
a[indi]

array([[30, 70],
       [40, 90]])

El indexado sofisticado funciona también en múltiples dimensiones. Veámoslo en el siguiente ejemplo:

In [45]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Como en la indexación estándar, el primer índice hace referencia a las filas y el segundo a las columnas:

In [46]:
fila =[0,1,2]
colu=[2,1,3]

a[fila,colu]


array([ 2,  5, 11])

Los valores el en arreglo corresponden a `a[0,2]`, `a[1,1]` y `a[2,3]` respectivamente.